/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/routerDemo/index" |
       "/pages/echartsShow/index" |
       "/pages/index/index" |
       "/pages/layoutDemo/index" |
       "/pages/piniaDemo/index" |
       "/pages/queryDemo/loginDemo" |
       "/pages/queryDemo/queryTestDemo" |
       "/pages/queryDemo/useRequestDemo" |
       "/pages/queryDemo/zPagingDemo" |
       "/pages/routerDemo/login" |
       "/pages/routerDemo/page1" |
       "/pages/routerDemo/page2" |
       "/pages/routerDemo/page3" |
       "/pages-sub/subDemo/index" |
       "/pages-sub/testDemo/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void
}
